version: "3.9"
services:
  web:
    build: ./client
    ports:
      - "5000:5000"
    volumes:
      - .:/client
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - .:/server
  redis:
    image: "redis:alpine"
